using UnityEngine;
using System.Collections;

public class EnemyManager2 : CEnemyManager
{
	EnemyStatus Bat_F = new EnemyStatus(Enemy.Bat_F, 400f, 3f, 0f, 800f, 0, 1);
	EnemyStatus Bat_FG = new EnemyStatus(Enemy.Bat_F, 400f, 3f, 0f, 800f, 0, 1);
	EnemyStatus Bat_FA = new EnemyStatus(Enemy.Bat_F, 600f, 300f, 100f, 800f, 0, 1);
	EnemyStatus ChampBat_F = new EnemyStatus(Enemy.ChampBat_F, 50f, 7000f, 100f, 800f, 20, 200000);

    public override void ManageStage()
    {
        
		StartCoroutine (SummonEnemy (2f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (3f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (4f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (5f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (6f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (7f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (8f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (9f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (10f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (11f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (12f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (13f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (14f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (15f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (16f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (17f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (18f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (19f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (20f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (21f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (22f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (23f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (24f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (25f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (26f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (27f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (28f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (29f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (30f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (31f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (32f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (33f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (34f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (35f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (36f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (37f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (38f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (39f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (40f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (41f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (42f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (43f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (44f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (45f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (46f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (47f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (48f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (49f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (50f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (51f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (52f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (53f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (54f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (55f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (56f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (57f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (58f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (59f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (60f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (61f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (62f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (63f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (64f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (65f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (66f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (67f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (68f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (69f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (70f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (71f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (72f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (73f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (74f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (75f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (76f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (77f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (78f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (79f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (80f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (81f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (82f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (83f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (84f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (85f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (86f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (87f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (88f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (89f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (90f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (91f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (92f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (93f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (94f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (95f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (96f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (97f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho

		StartCoroutine (SummonEnemy (2f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (3f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (4f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (5f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (6f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (7f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (8f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (9f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (10f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (11f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (12f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (13f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (14f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (15f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (16f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (17f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (18f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (19f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (20f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (21f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (22f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (23f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (24f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (26f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (27f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (28f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (29f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (30f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (31f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (32f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (33f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (34f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (35f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (36f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (37f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (38f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (39f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (40f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (41f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (42f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (43f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (44f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (45f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (46f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (47f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (48f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (49f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (50f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (51f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (52f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (53f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (54f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (55f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (56f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (57f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (58f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (59f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (60f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (61f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (62f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (63f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (64f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (65f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (66f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (67f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (68f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (69f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (70f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (71f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (72f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (73f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (74f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (75f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (76f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (77f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (78f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (79f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (80f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (81f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (82f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (83f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TL, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (84f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br1, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (85f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T1, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (86f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br2, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (87f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T2, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (88f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br3, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (89f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T3, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (90f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br4, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (91f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T4, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (92f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br5, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (93f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T5, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (94f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br6, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (95f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T6, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (96f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.Br7, 0.1f, 7)); //sho	
		StartCoroutine (SummonEnemy (97f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.T7, 0.1f, 7)); //sho
		StartCoroutine (SummonEnemy (98f, 12, Bat_F, CEnemy.AI.Go, CEnemy.StartPosition.TR, 0.1f, 7)); //sho

		StartCoroutine (SummonEnemy (100f, 1, ChampBat_F, CEnemy.AI.C_RE, CEnemy.StartPosition.T4, 2f, 1)); //sho

        StartCoroutine(AsClearBoss(100.1f));
    }
}
